import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from "react";
import {CLOSED, OPEN, SITE_URL} from "../constants";
import axios from "axios";

const Home: NextPage = () => {
    const [doorStatus, setDoorStatus] = useState<'open'|'close'>('close');
    useEffect(() => {
        const interval = setInterval(() => {
              axios.get<{door: 'open'| 'close'}>(SITE_URL)
                .then(({data}) => setDoorStatus(data.door));
        }, 200);


        return () => clearInterval(interval);
    }, []);

    const formatStatus = () => doorStatus === 'open' ? OPEN : CLOSED

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Status:
        </h1>

        <p className={styles.description}>
            {formatStatus()}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
